{"uuid": "b1a614a9-4dd4-4313-b3ee-d6acf940ce77", "children": ["76df3b9b-2471-46d4-afbb-e43bb67159c5"], "befores": [{"name": "login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF708F48EF2+54786]\n\t(No symbol) [0x00007FF708EB5612]\n\t(No symbol) [0x00007FF708D6A64B]\n\t(No symbol) [0x00007FF708D4A9F5]\n\t(No symbol) [0x00007FF708DD0887]\n\t(No symbol) [0x00007FF708DE43CF]\n\t(No symbol) [0x00007FF708DCBC43]\n\t(No symbol) [0x00007FF708DA0941]\n\t(No symbol) [0x00007FF708DA1B84]\n\tGetHandleVerifier [0x00007FF709297F52+3524194]\n\tGetHandleVerifier [0x00007FF7092ED800+3874576]\n\tGetHandleVerifier [0x00007FF7092E5D7F+3843215]\n\tGetHandleVerifier [0x00007FF708FE5086+694166]\n\t(No symbol) [0x00007FF708EC0A88]\n\t(No symbol) [0x00007FF708EBCA94]\n\t(No symbol) [0x00007FF708EBCBC2]\n\t(No symbol) [0x00007FF708EACC83]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 39, in login_page\n    page.load()\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\pages\\login_page.py\", line 19, in load\n    self.browser.get(self.url)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698152674342, "stop": 1698152674345}], "start": 1698152674342, "stop": 1698152674434}