{"uuid": "08d9c9dd-f05f-4a43-ba21-726961368949", "children": ["d9b7959e-8283-49dd-aacc-b7719aef7c5a", "40d8e689-5d5e-4fb2-a31c-5e5f98f8d42f", "7df08ef7-8fda-441f-bba8-557515a30ac2", "382f6cbd-6cda-4a89-9b11-6873ed9b6d8d", "aee86dba-59ea-4763-9743-d75cde077ea0", "35785f51-7262-443b-ae0d-dd60e99d617c", "28ef2c58-9b0f-49dd-8595-a8aa09ee8890", "49c8f7a7-eaec-4955-9da1-9734c3bf19ce", "2e288a59-f30c-454c-a88c-9049fc7d835e", "c55b2c4b-55e9-4565-b770-f01ce51416db", "72e455cf-cf77-47fb-91f6-bcde9cb820c3", "4050be79-bd1d-4998-85fb-6d65212af0e3", "74af2dab-b70c-4039-bf2b-9a48707c022f", "ca47d9eb-a5c7-4eed-8f7b-e7610c88a41c", "2c972d21-da40-4947-a086-01fd2c1d50c0", "4e68c7c0-3ee1-491f-86c7-08acd4ad230b", "21cc578b-3059-4b4e-88ab-adfd56fa25d4"], "befores": [{"name": "browser", "status": "passed", "start": 1698097937408, "stop": 1698097938727}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6A5137D32+55474]\n\t(No symbol) [0x00007FF6A50A77E2]\n\t(No symbol) [0x00007FF6A4F5E0EB]\n\t(No symbol) [0x00007FF6A4F3E528]\n\t(No symbol) [0x00007FF6A4FC3B77]\n\t(No symbol) [0x00007FF6A4FD75BF]\n\t(No symbol) [0x00007FF6A4FBEF33]\n\t(No symbol) [0x00007FF6A4F93D41]\n\t(No symbol) [0x00007FF6A4F94F84]\n\tGetHandleVerifier [0x00007FF6A549B772+3609330]\n\tGetHandleVerifier [0x00007FF6A54F1A90+3962384]\n\tGetHandleVerifier [0x00007FF6A54E9F1F+3930783]\n\tGetHandleVerifier [0x00007FF6A51D3CC6+694342]\n\t(No symbol) [0x00007FF6A50B2238]\n\t(No symbol) [0x00007FF6A50AE4A4]\n\t(No symbol) [0x00007FF6A50AE5D2]\n\t(No symbol) [0x00007FF6A509EE33]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 29, in browser\n    driver.save_screenshot(os.path.join(screenshot_dir, screenshot_name))\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 917, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 893, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698097956517, "stop": 1698097956522}], "start": 1698097937408, "stop": 1698097956522}