{"uuid": "d77f806c-7afc-4397-af34-2c27c0498cab", "children": ["21cc578b-3059-4b4e-88ab-adfd56fa25d4"], "befores": [{"name": "login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6A5137D32+55474]\n\t(No symbol) [0x00007FF6A50A77E2]\n\t(No symbol) [0x00007FF6A4F5E0EB]\n\t(No symbol) [0x00007FF6A4F3E528]\n\t(No symbol) [0x00007FF6A4FC3B77]\n\t(No symbol) [0x00007FF6A4FD75BF]\n\t(No symbol) [0x00007FF6A4FBEF33]\n\t(No symbol) [0x00007FF6A4F93D41]\n\t(No symbol) [0x00007FF6A4F94F84]\n\tGetHandleVerifier [0x00007FF6A549B772+3609330]\n\tGetHandleVerifier [0x00007FF6A54F1A90+3962384]\n\tGetHandleVerifier [0x00007FF6A54E9F1F+3930783]\n\tGetHandleVerifier [0x00007FF6A51D3CC6+694342]\n\t(No symbol) [0x00007FF6A50B2238]\n\t(No symbol) [0x00007FF6A50AE4A4]\n\t(No symbol) [0x00007FF6A50AE5D2]\n\t(No symbol) [0x00007FF6A509EE33]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 45, in login_page\n    page.load()\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\pages\\login_page.py\", line 19, in load\n    self.browser.get(self.url)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698097956348, "stop": 1698097956350}], "start": 1698097956348, "stop": 1698097956514}