{"uuid": "f901e219-9666-44d6-b0b0-9a131e192049", "children": ["929621f8-42fe-4abc-9712-4b13dd9ff152"], "befores": [{"name": "login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF760608EF2+54786]\n\t(No symbol) [0x00007FF760575612]\n\t(No symbol) [0x00007FF76042A64B]\n\t(No symbol) [0x00007FF76040A9F5]\n\t(No symbol) [0x00007FF760490887]\n\t(No symbol) [0x00007FF7604A43CF]\n\t(No symbol) [0x00007FF76048BC43]\n\t(No symbol) [0x00007FF760460941]\n\t(No symbol) [0x00007FF760461B84]\n\tGetHandleVerifier [0x00007FF760957F52+3524194]\n\tGetHandleVerifier [0x00007FF7609AD800+3874576]\n\tGetHandleVerifier [0x00007FF7609A5D7F+3843215]\n\tGetHandleVerifier [0x00007FF7606A5086+694166]\n\t(No symbol) [0x00007FF760580A88]\n\t(No symbol) [0x00007FF76057CA94]\n\t(No symbol) [0x00007FF76057CBC2]\n\t(No symbol) [0x00007FF76056CC83]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 39, in login_page\n    page.load()\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\pages\\login_page.py\", line 19, in load\n    self.browser.get(self.url)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698151619049, "stop": 1698151619052}], "start": 1698151619049, "stop": 1698151619178}