[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFAE7438B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/347272714c270208f069752c2ba5eaf5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFAE743F40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/347272714c270208f069752c2ba5eaf5/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFAE743E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/347272714c270208f069752c2ba5eaf5/url